---
name: checks on Pull Request
"on":
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: >-
            ${{ github.event_name == 'merge_group' &&
            github.event.merge_group.head_sha ||
            github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.lock
      - name: Run gitlint on CI with pre-commit
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "merge_group" ]; then
            base="${{ github.event.merge_group.base_sha }}"
            head="${{ github.event.merge_group.head_sha }}"
            gitlint --commits "${base}..${head}"
          else
            gitlint --commits \
              "origin/${{ github.event.pull_request.base.ref }}..HEAD"
          fi
